name: "test-pr-supporter"
on: 
  pull_request:
    types: [opened]
    
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: test
      uses: Im-D/Im-Bot/packages/update-readme@update-readme
      with:
        myToken: ${{ secrets.GITHUB_TOKEN }}

