name: "test-pr-supporter"
on: 
  pull_request:
    types: [opened]
      

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: test
      uses: Im-D/Im-Bot/packages/pr-supporter@master
      with:
        myToken: ${{ secrets.GITHUB_TOKEN }}
        
    - name: pr-reviewer-test
      uses: Im-D/Im-Bot/packages/pr-supporter@pr-reviewer-dev
      with:
        myToken: ${{ secrets.GITHUB_TOKEN }}
